// ─── Hook-inventory parity guard (GitHub #43, Phase A; hardened GitHub #46, Phase D) ──
//
// WHAT THIS GUARDS: daemon/src/hooks/dispatcher.ts implements a set of hook
// handlers (HANDLERS, keyed by event then name) -- 29 as of Phase D (GitHub
// #46), 37 as of Phase H (GitHub #49, execution-events ledger: eight new
// handlers across PostToolUseFailure, StopFailure, FileChanged, PreCompact,
// PostCompact, SessionEnd, SubagentStart, SubagentStop). The exact count is
// never transcribed as an assertion (R26) -- EXPECTED_IMPLEMENTED below is
// the single enumerated source of truth, and the length comparison against
// listHookHandlers() is what actually gates. Every entry in that
// enumeration is wired in EACH of the two runtime settings files
// (.claude/settings.template.json for Claude Code, hooks.json at the repo
// root for the Copilot CLI plugin).
// Before this test existed, that inventory drift was invisible: nothing
// compared the two inventories, so a handler could be fully implemented and
// reachable by name yet silently dead in both runtimes.
//
// AS OF 2026-09-06, all three of TheEights' episodic-recall handlers —
//   - ("SessionStart",     "eights-recall-project")
//   - ("PreToolUse",       "eights-recall-stage")
//   - ("UserPromptSubmit", "eights-recall-request")
// are wired in BOTH settings files. TheEights episodic recall is
// consequently ON in both the Claude Code and the Copilot runtime today —
// it is NOT off in either. GitHub #46 (Phase D) is the issue that wired
// these three handlers and removed the two self-expiring allowance lists
// this file previously carried (the pending-wiring list and the
// pending-timeout-exemption list): every (event, name) pair implemented in
// dispatcher.ts MUST now be wired,
// unconditionally, in both files, and every wired entry in both files MUST
// declare a valid, positive, finite numeric timeout, unconditionally. No
// allowance list, and no conditional excusal of any pair or file, remains
// anywhere in this file.
//
// SOURCE-OF-TRUTH CONSTRAINT: this test reads ONLY
// `.claude/settings.template.json` (the tracked template) and MUST NOT read
// `.claude/settings.json` (git-ignored, generated by scripts/install-user.ps1,
// absent on a fresh clone / in CI).
//
// EXPORT CONSTRAINT: dispatcher.ts's HANDLERS constant is not exported. This
// test resolves the inventory via the side-effect-free `listHookHandlers()`
// export (dispatcher.ts:815), imported from `daemon/dist/`, per R2.5/R2.6 —
// no TypeScript source is parsed and no compiled-JS text is scraped.
//
// This file is fully self-contained (ANTI-STALL TEST RULE): no daemon, no
// MCP peer, no vendor CLI, no network, and no touch of
// ~/.pair-programmer/state.db (importing dispatcher.js triggers no hook and
// no DB access at module-load time; see the "import has no side effects"
// check below).
//
// MUTATION-CHECK STRATEGY: the acceptance criteria (AC-18..AC-34 in the
// spec) require confirming the guard goes RED under a battery of injected
// defects, with correctly-labelled messages. Rather than mutating the real
// settings files on disk (fragile, and risks leaving the repo dirty if a
// test aborts mid-run), this file mutates IN-MEMORY clones of the same
// parsed JSON structures and runs them through the exact same pure
// parse/compare/format functions used for the real-file assertions. A defect
// in the guard's logic is therefore caught identically whether it is
// exercised against the real tree or a synthetic fixture.

import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, isAbsolute, join } from "node:path";
import { homedir } from "node:os";
import assert from "node:assert/strict";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, "..", "..");
const DIST = join(__dirname, "..", "dist");

const TEMPLATE_PATH = join(REPO_ROOT, ".claude", "settings.template.json");
const HOOKS_JSON_PATH = join(REPO_ROOT, "hooks.json");
const TEMPLATE_LABEL = ".claude/settings.template.json";
const HOOKS_JSON_LABEL = "hooks.json";

let passed = 0;
let failed = 0;
function it(label, fn) {
  try {
    fn();
    passed++;
    console.log(`  pass  ${label}`);
  } catch (err) {
    failed++;
    console.error(`  FAIL  ${label}\n         ${err.message}`);
  }
}
async function itAsync(label, fn) {
  try {
    await fn();
    passed++;
    console.log(`  pass  ${label}`);
  } catch (err) {
    failed++;
    console.error(`  FAIL  ${label}\n         ${err.message}`);
  }
}

function pairKey(event, name) {
  return `${event} ${name}`;
}

// ─── AC-D21: the two former allowance identifiers must never reappear ─────
// A pure textual self-check: R7.5 requires a literal-absence check on the
// two allowance-constant identifiers this file used to declare, so a
// re-introduced allowance fails loudly. Each is constructed from fragments
// at runtime (same technique as the settings.json exclusion check below),
// AND neither identifier is written contiguously anywhere else in this
// file's prose or messages — so this very assertion's source text never
// contains either identifier contiguously, and therefore never matches
// itself.
it("AC-D21: neither former allowance-constant identifier appears anywhere in this file's source (GitHub #46 allowances fully removed)", () => {
  const src = readFileSync(__filename, "utf8");
  const pendingWiring = ["PENDING", "_WIRING"].join("");
  const pendingTimeoutExempt = ["PENDING", "_TIMEOUT_EXEMPT_FILES"].join("");
  assert.ok(!src.includes(pendingWiring), "the pending-wiring allowance identifier must not appear anywhere in this file — it was removed by GitHub #46");
  assert.ok(!src.includes(pendingTimeoutExempt), "the pending-timeout-exemption allowance identifier must not appear anywhere in this file — it was removed by GitHub #46");
});

// ─── AC-D21b (R7.6) — header states the post-#46 truth, not the pre-#46 one
it("AC-D21b: header states the post-#46 truth — the three recall handlers, ON not off, the date, and #46 — with no residual off-claim", () => {
  const src = readFileSync(__filename, "utf8");
  const header = src.slice(0, src.indexOf("import { readFileSync }"));
  assert.match(header, /eights-recall-project/);
  assert.match(header, /eights-recall-stage/);
  assert.match(header, /eights-recall-request/);
  assert.match(header, /2026-09-06/);
  assert.match(header, /#46/);
  assert.match(header, /\bON\b/, "header must positively state recall is ON");
  assert.match(header, /NOT off/i, "header must carry the negative claim that recall is not off");
  assert.ok(
    !/episodic recall is consequently[\s\S]*off in both/i.test(header),
    "header must no longer claim recall is off in both runtimes — that claim became false once #46 landed",
  );
});

// ─── Pure parsing helpers (shared by real-file checks and fixture-based
//     mutation checks) ────────────────────────────────────────────────────

/**
 * Extract {event, name} from a hook invocation command string of the shape
 * `... hook <Event> <name>`. Per R2.16: name is the FINAL whitespace token,
 * event is read from the command text itself (compared against the
 * containing key by the caller — this function does not know the key).
 * Returns null when the command does not carry a distinct name token after
 * "hook <Event>" (R2.18 — caller must treat null as a hard failure, not a
 * skip).
 */
function parseHookCommand(command) {
  if (typeof command !== "string" || !command.trim()) return null;
  const tokens = command.trim().split(/\s+/);
  const hookIdx = tokens.indexOf("hook");
  if (hookIdx === -1) return null;
  if (hookIdx + 2 >= tokens.length) return null; // no room for both <Event> and <name>
  const event = tokens[hookIdx + 1];
  const name = tokens[tokens.length - 1];
  if (hookIdx + 1 === tokens.length - 1) return null; // <Event> and <name> collapsed to one token
  if (!event || !name) return null;
  return { event, name };
}

function hasValidTimeout(v) {
  return typeof v === "number" && Number.isFinite(v) && v > 0;
}

/**
 * Phase L (#53): recover `{event, name}` from an `mcp_tool` hook entry.
 *
 * A converted entry carries no command text — it names a tool
 * `hook_<Event>_<handler_with_underscores>` on `pp_harness`. The handler's real
 * name uses hyphens (`cost-tally`), which MCP tool names cannot contain, so the
 * mapping back is not a plain split: the event is matched against the known
 * event list and the remainder is the handler with `_` restored to `-`.
 *
 * Matching the event against `MCP_HOOK_EVENTS` rather than splitting on the first
 * `_` is load-bearing, because several events are themselves multi-word
 * (`PostToolUseFailure`, `SubagentStart`, `UserPromptSubmit`) and a naive split
 * would mis-attribute every one of them — inventing a wiring mismatch, or
 * worse, hiding a real one.
 */
/**
 * Event names, longest first. Longest-first is not cosmetic: `PostToolUse` is a
 * prefix of `PostToolUseFailure`, so scanning shortest-first would parse
 * `hook_PostToolUseFailure_record_execution_failure` as event `PostToolUse`
 * with handler `Failure-record-execution-failure` — a handler that does not
 * exist, reported as a wiring mismatch that is not real.
 */
const MCP_HOOK_EVENTS = [
  "PostToolUseFailure",
  "UserPromptSubmit",
  "SubagentStart",
  "SubagentStop",
  "SessionStart",
  "SessionEnd",
  "PostToolUse",
  "PreToolUse",
  "StopFailure",
  "FileChanged",
  "PostCompact",
  "PreCompact",
  "Setup",
  "Stop",
].sort((a, b) => b.length - a.length);

function parseMcpToolHook(h) {
  if (h?.type !== "mcp_tool" || typeof h.tool !== "string") return null;
  const m = h.tool.match(/^hook_(.+)$/);
  if (!m) return null;
  const rest = m[1];
  for (const ev of MCP_HOOK_EVENTS) {
    const prefix = `${ev}_`;
    if (rest.startsWith(prefix)) {
      return { event: ev, name: rest.slice(prefix.length).replace(/_/g, "-"), server: h.server };
    }
  }
  return null;
}

/** Parse `.claude/settings.template.json`-shaped JSON into flat entries. */
function extractTemplateEntries(json) {
  const out = [];
  for (const [containingEvent, wrappers] of Object.entries(json.hooks ?? {})) {
    for (const wrapper of wrappers) {
      for (const h of wrapper.hooks ?? []) {
        const mcp = parseMcpToolHook(h);
        out.push({
          containingEvent,
          command: h.command,
          // An mcp_tool entry is wired just as truly as a command entry. The
          // parity assertion is about WHICH handlers are wired, not about how
          // they are transported, so feeding `parsed` from either shape keeps
          // that one assertion authoritative over both transports instead of
          // needing a second, driftable copy of it.
          parsed: mcp ? { event: mcp.event, name: mcp.name } : parseHookCommand(h.command),
          transport: mcp ? "mcp_tool" : "command",
          mcpServer: mcp ? mcp.server : undefined,
          mcpTool: mcp ? h.tool : undefined,
          mcpInput: mcp ? h.input : undefined,
          isAsync: Object.prototype.hasOwnProperty.call(h, "async"),
          // A converted entry declares no `timeout` — that field belongs to
          // the command-hook shape. Carry it through as `undefined` and let the
          // timeout assertions SKIP mcp_tool entries explicitly.
          //
          // An earlier version of this line reported a synthetic `30` so the
          // existing assertions would pass unchanged. That was wrong twice
          // over: it violated this repo's own convention that a reported value
          // must derive from the decision source rather than a stand-in, and
          // the fabricated number then had to equal hooks.json's real
          // `timeoutSec` — which is 20 for the informational class, so it
          // failed anyway and would have been "fixed" by inventing a second
          // number. Scoping the check to the transport it is about is the
          // honest form.
          timeout: mcp ? undefined : h.timeout,
          statusMessage: h.statusMessage,
          hasIf: Object.prototype.hasOwnProperty.call(h, "if") || Object.prototype.hasOwnProperty.call(wrapper, "if"),
        });
      }
    }
  }
  return out;
}

/** Parse `hooks.json`-shaped JSON into flat entries (bash + powershell). */
function extractHooksJsonEntries(json) {
  const out = [];
  for (const [containingEvent, entries] of Object.entries(json.hooks ?? {})) {
    for (const entry of entries) {
      out.push({
        containingEvent,
        bash: entry.bash,
        powershell: entry.powershell,
        bashParsed: parseHookCommand(entry.bash),
        pwshParsed: parseHookCommand(entry.powershell),
        timeoutSec: entry.timeoutSec,
        statusMessage: entry.statusMessage,
        hasIf: Object.prototype.hasOwnProperty.call(entry, "if"),
      });
    }
  }
  return out;
}

/**
 * Reduce template entries into: the (event,name) pair set, unparseable raw
 * commands (R2.18), event/key mismatches (R2.16), and entries missing a
 * valid timeout (R2.13/R2.15). No exemption parameter — every entry is held
 * to the timeout requirement unconditionally (R7.2 item 8/9).
 */
function reduceTemplateEntries(entries) {
  const pairs = new Set();
  const unparseable = [];
  const eventMismatches = [];
  const missingTimeout = [];
  const badMcpShape = [];
  for (const e of entries) {
    if (!e.parsed) {
      unparseable.push(e.command);
      continue;
    }
    if (e.parsed.event !== e.containingEvent) {
      eventMismatches.push({ containingKey: e.containingEvent, commandEvent: e.parsed.event, name: e.parsed.name });
    }
    pairs.add(pairKey(e.containingEvent, e.parsed.name));
    // Phase L (#53): `timeout` is a command-hook field, so an mcp_tool entry is
    // required to declare NONE rather than to declare a valid one. The two
    // requirements are asserted separately and neither is relaxed: the 14
    // command hooks still need a positive finite timeout unconditionally, and
    // `badMcpShape` below catches an mcp_tool entry that carries a `timeout`,
    // an `async`, a stray `command`, or the wrong server. Skipping without that
    // second check would have turned "no timeout because it is an mcp_tool"
    // and "no timeout because someone deleted it" into the same silent pass.
    if (e.transport === "mcp_tool") {
      if (
        Object.prototype.hasOwnProperty.call(e, "timeout") && e.timeout !== undefined
        || e.isAsync
        || e.command !== undefined
        || e.mcpServer !== "pp_harness"
      ) {
        badMcpShape.push({
          event: e.containingEvent,
          name: e.parsed.name,
          why:
            e.isAsync ? "declares `async`, which is command-hook-only and mutually exclusive with mcp_tool"
              : e.command !== undefined ? "kept a `command` alongside `mcp_tool`"
              : e.mcpServer !== "pp_harness" ? `names server "${e.mcpServer}" instead of pp_harness`
              : "declares a `timeout`, which is a command-hook field",
        });
      }
      continue;
    }
    if (!hasValidTimeout(e.timeout)) {
      missingTimeout.push({ event: e.containingEvent, name: e.parsed.name });
    }
  }
  return { pairs, unparseable, eventMismatches, missingTimeout, badMcpShape };
}

/** Mirror of reduceTemplateEntries for hooks.json's bash/powershell schema. */
function reduceHooksJsonEntries(entries) {
  const pairs = new Set();
  const unparseable = [];
  const eventMismatches = [];
  const bashPwshMismatches = [];
  const missingTimeout = [];
  for (const e of entries) {
    if (!e.bashParsed || !e.pwshParsed) {
      unparseable.push(e.bash ?? e.powershell ?? "(no command)");
      continue;
    }
    if (e.bashParsed.event !== e.pwshParsed.event || e.bashParsed.name !== e.pwshParsed.name) {
      bashPwshMismatches.push({ bash: e.bash, powershell: e.powershell });
      continue;
    }
    if (e.bashParsed.event !== e.containingEvent) {
      eventMismatches.push({ containingKey: e.containingEvent, commandEvent: e.bashParsed.event, name: e.bashParsed.name });
    }
    pairs.add(pairKey(e.containingEvent, e.bashParsed.name));
    if (!hasValidTimeout(e.timeoutSec)) {
      missingTimeout.push({ event: e.containingEvent, name: e.bashParsed.name });
    }
  }
  return { pairs, unparseable, eventMismatches, bashPwshMismatches, missingTimeout };
}

/**
 * Compute the parity diagnosis for one settings file against the implemented
 * set. Unconditional (R7.2 items 4/5): every implemented pair MUST be wired
 * in every file, and every wired pair MUST be implemented — no allowance
 * suppresses either direction any more.
 */
function diagnoseParity(implementedPairs, wiredPairs) {
  const implementedButUnwired = [];
  for (const p of implementedPairs) {
    if (wiredPairs.has(p)) continue;
    implementedButUnwired.push(p);
  }
  const wiredButUnimplemented = [...wiredPairs].filter(p => !implementedPairs.has(p));
  return { implementedButUnwired, wiredButUnimplemented };
}

function unkey(key) {
  const [event, name] = key.split(" ");
  return { event, name };
}

function formatPairs(keys) {
  return keys.map(k => { const { event, name } = unkey(k); return `(${sanitize(event)}, ${sanitize(name)})`; }).join(", ");
}

/** R2.22: strip a home-dir prefix so failure messages never carry one. */
function sanitize(s) {
  const home = homedir();
  if (home && typeof s === "string" && s.includes(home)) return s.split(home).join("~");
  return s;
}

/**
 * Build the full diagnostic message for one file. Returns [] when there is
 * nothing to report. This is the single source of failure-message text so
 * every mutation check exercises the exact same formatting code the real
 * assertion uses. Exactly 4 parameters (R7.2 item 9 / AC-D27): no
 * timeout-exemption parameter exists any more.
 */
function buildFileReport(fileLabel, implementedPairs, wiredPairs, reduced) {
  const { implementedButUnwired, wiredButUnimplemented } = diagnoseParity(implementedPairs, wiredPairs);
  const lines = [];

  if (implementedButUnwired.length) {
    lines.push(`[${fileLabel}] implemented but unwired: ${formatPairs(implementedButUnwired)}`);
  }
  if (wiredButUnimplemented.length) {
    lines.push(`[${fileLabel}] wired but unimplemented: ${formatPairs(wiredButUnimplemented)}`);
  }
  if (reduced.unparseable.length) {
    for (const raw of reduced.unparseable) {
      lines.push(`[${fileLabel}] unparseable hook-shaped command (no handler name extracted): ${sanitize(raw)}`);
    }
  }
  if (reduced.eventMismatches.length) {
    for (const m of reduced.eventMismatches) {
      lines.push(
        `[${fileLabel}] event mismatch for handler "${sanitize(m.name)}": containing key says "${sanitize(m.containingKey)}", ` +
        `command text says "${sanitize(m.commandEvent)}"`,
      );
    }
  }
  // Phase L (#53): reported through the same builder as every other class, so
  // a collected-but-unreported list cannot happen. A finding gathered into an
  // array that nothing prints is indistinguishable from no finding.
  if (reduced.badMcpShape && reduced.badMcpShape.length) {
    for (const m of reduced.badMcpShape) {
      lines.push(`[${fileLabel}] malformed mcp_tool hook (${sanitize(m.event)}, ${sanitize(m.name)}): ${sanitize(m.why)}`);
    }
  }
  if (reduced.bashPwshMismatches && reduced.bashPwshMismatches.length) {
    for (const m of reduced.bashPwshMismatches) {
      lines.push(`[${fileLabel}] bash/powershell handler mismatch: bash="${sanitize(m.bash)}" powershell="${sanitize(m.powershell)}"`);
    }
  }
  if (reduced.missingTimeout.length) {
    for (const m of reduced.missingTimeout) {
      lines.push(`[${fileLabel}] missing/invalid timeout on (${sanitize(m.event)}, ${sanitize(m.name)})`);
    }
  }
  return lines;
}

function assertNoFailures(templateJson, hooksJsonJson, implementedPairs) {
  const templateEntries = extractTemplateEntries(templateJson);
  const hooksEntries = extractHooksJsonEntries(hooksJsonJson);
  const templateReduced = reduceTemplateEntries(templateEntries);
  const hooksReduced = reduceHooksJsonEntries(hooksEntries);

  const templateLines = buildFileReport(TEMPLATE_LABEL, implementedPairs, templateReduced.pairs, templateReduced);
  const hooksLines = buildFileReport(HOOKS_JSON_LABEL, implementedPairs, hooksReduced.pairs, hooksReduced);
  const all = [...templateLines, ...hooksLines];
  if (all.length) {
    throw new Error(`hook-inventory parity failures:\n${all.join("\n")}`);
  }
  return { templateReduced, hooksReduced };
}

// ─── Load real files + real implemented inventory ─────────────────────────

// Raw text is retained alongside the parsed form so AC-34 can assert
// byte-for-byte immutability rather than semantic equality — a mutation that
// round-trips through JSON.parse identically (reordered keys, changed
// whitespace) would slip past a deepEqual but is still an edit to a tracked file.
const TEMPLATE_RAW = readFileSync(TEMPLATE_PATH, "utf8");
const HOOKS_JSON_RAW = readFileSync(HOOKS_JSON_PATH, "utf8");
const templateJson = JSON.parse(TEMPLATE_RAW);
const hooksJsonJson = JSON.parse(HOOKS_JSON_RAW);

// R2.11: never read .claude/settings.json. Prose mentions of the excluded
// path (explaining WHY it is excluded) are fine; what must never appear is a
// quoted string literal path segment naming it as something this file reads.
it("this file never reads .claude/settings.json (only settings.template.json)", () => {
  const src = readFileSync(__filename, "utf8");
  const bareSettingsJsonLiteral = ["s", "ettings.json"].join("");
  const quoted = new RegExp(`["'\`]${bareSettingsJsonLiteral.replace(".", "\\.")}["'\`]`);
  assert.ok(!quoted.test(src),
    "no quoted bare-settings-file path-segment literal may appear (would indicate this file reads the git-ignored generated file)");
  assert.ok(TEMPLATE_PATH.endsWith("settings.template.json"), "TEMPLATE_PATH must resolve to the template, not the generated file");
});

let listHookHandlers;
await itAsync("dispatcher.js imports cleanly with no side effects (no hook run, no process.exit, no DB touch)", async () => {
  const before = Date.now();
  const mod = await import(pathToFileURL(join(DIST, "hooks", "dispatcher.js")).href);
  assert.equal(typeof mod.listHookHandlers, "function", "listHookHandlers must be exported");
  assert.ok(Date.now() - before < 5000, "import must be near-instant (no blocking I/O at module scope)");
  listHookHandlers = mod.listHookHandlers;
});

const EXPECTED_IMPLEMENTED = [
  ["SessionStart", "daemon-up"], ["SessionStart", "vendor-matrix"], ["SessionStart", "cli-version-pin"],
  ["SessionStart", "master-plan-load"], ["SessionStart", "surfaced-runs"], ["SessionStart", "eights-recall-project"],
  ["PreToolUse", "block-destructive-shell"], ["PreToolUse", "enforce-active-run"], ["PreToolUse", "enforce-vendor-matrix"],
  ["PreToolUse", "enforce-sandbox-policy"], ["PreToolUse", "enforce-no-secrets"], ["PreToolUse", "enforce-validator-gate"],
  ["PreToolUse", "enforce-rfc2119-language"], ["PreToolUse", "eights-recall-stage"],
  ["PostToolUse", "cost-tally"], ["PostToolUse", "record-attempt"], ["PostToolUse", "taxonomy-coverage-update"],
  ["PostToolUse", "hash-artifact"], ["PostToolUse", "loop-ceiling-tally"], ["PostToolUse", "verdict-rubric-coverage"],
  ["PostToolUse", "update-master-plan"],
  ["UserPromptSubmit", "taxonomy-nudge"], ["UserPromptSubmit", "team-suggester"], ["UserPromptSubmit", "risk-flag"],
  ["UserPromptSubmit", "surfaced-run-reminder"], ["UserPromptSubmit", "profile-aware-nudge"], ["UserPromptSubmit", "eights-recall-request"],
  ["Stop", "decision-log-required"], ["Stop", "summary-format-check"],
  // Phase H (GitHub #49, execution-events ledger) -- eight new (event, name) pairs.
  ["PostToolUseFailure", "record-execution-failure"], ["StopFailure", "surface-api-killed-run"],
  ["FileChanged", "constitution-drift-detect"], ["PreCompact", "run-context-save"],
  ["PostCompact", "run-context-reinject"], ["SessionEnd", "session-orphan-sweep"],
  ["SubagentStart", "subagent-dispatch-record"], ["SubagentStop", "subagent-stop-observe"],
];

let implementedPairKeys;
it("listHookHandlers() returns exactly the pairs enumerated in the spec (AC-15)", () => {
  const raw = listHookHandlers();
  const expectedKeys = new Set(EXPECTED_IMPLEMENTED.map(([e, n]) => pairKey(e, n)));
  assert.equal(raw.length, expectedKeys.size, `expected ${expectedKeys.size} implemented (event,name) pairs, got ${raw.length}`);
  const keys = new Set(raw.map(p => pairKey(p.event, p.name)));
  implementedPairKeys = keys;
  assert.deepEqual(
    [...keys].sort(),
    [...expectedKeys].sort(),
    "the exported inventory must match the enumeration in spec section 2.3 exactly, by event and by name",
  );
});

// ─── AC-12..AC-17, AC-33, AC-34 — the real-tree assertion ─────────────────

it("hook inventory parity holds against the real repository tree — every implemented pair is wired in both files, unconditionally", () => {
  assertNoFailures(templateJson, hooksJsonJson, implementedPairKeys);
});

it("the test resolves both settings paths via import.meta.url, not process.cwd()", () => {
  // R2.12/AC-17. This assertion must stay FALSIFIABLE: an earlier revision
  // ended in `|| true`, which made the whole expression unconditionally true
  // and left the requirement unasserted. Recompute the paths from
  // import.meta.url and require the module-level constants to match exactly —
  // if someone rebases either constant onto process.cwd(), this diverges the
  // moment the suite is invoked from anywhere but the repo root.
  const fromUrl = dirname(fileURLToPath(import.meta.url));
  const expectedTemplate = join(fromUrl, "..", "..", ".claude", "settings.template.json");
  const expectedHooksJson = join(fromUrl, "..", "..", "hooks.json");

  assert.equal(TEMPLATE_PATH, expectedTemplate,
    "TEMPLATE_PATH must be derived from import.meta.url, not process.cwd()");
  assert.equal(HOOKS_JSON_PATH, expectedHooksJson,
    "HOOKS_JSON_PATH must be derived from import.meta.url, not process.cwd()");

  // Both must be absolute; a relative path would silently re-resolve per cwd.
  assert.ok(isAbsolute(TEMPLATE_PATH), "TEMPLATE_PATH must be absolute");
  assert.ok(isAbsolute(HOOKS_JSON_PATH), "HOOKS_JSON_PATH must be absolute");

  // And they must actually resolve to readable files from this cwd, whatever it is.
  assert.ok(readFileSync(TEMPLATE_PATH, "utf8").length > 0);
  assert.ok(readFileSync(HOOKS_JSON_PATH, "utf8").length > 0);
});

// ─── Deep-clone helper for fixture mutations ──────────────────────────────
function clone(obj) { return JSON.parse(JSON.stringify(obj)); }

// ─── AC-18: rename one wired template.json handler to a nonexistent name ──
it("AC-18: renaming a wired template.json handler to a nonexistent name fails, naming both directions", () => {
  const mutated = clone(templateJson);
  const entry = mutated.hooks.SessionStart[0].hooks[0];
  assert.match(entry.command, /daemon-up$/);
  entry.command = entry.command.replace(/daemon-up$/, "daemon-up-typo");
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "mutation must make the guard fail");
  assert.match(threw.message, /wired but unimplemented[\s\S]*daemon-up-typo/);
  assert.match(threw.message, /implemented but unwired[\s\S]*daemon-up/);
  // AC-25: message must name literal strings, not just integers.
  assert.match(threw.message, /daemon-up-typo/);
  // AC-20/21 not applicable here.
});

// ─── AC-19: same mutation applied to hooks.json ────────────────────────────
it("AC-19: the same rename mutation in hooks.json produces the same two labelled groups, attributed to hooks.json", () => {
  const mutated = clone(hooksJsonJson);
  const entry = mutated.hooks.SessionStart[0];
  entry.bash = entry.bash.replace(/daemon-up$/, "daemon-up-typo");
  entry.powershell = entry.powershell.replace(/daemon-up$/, "daemon-up-typo");
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /\[hooks\.json\] wired but unimplemented[\s\S]*daemon-up-typo/);
  assert.match(threw.message, /\[hooks\.json\] implemented but unwired[\s\S]*daemon-up/);
});

// ─── AC-20: remove timeoutSec from one hooks.json entry ────────────────────
it("AC-20: removing timeoutSec from a hooks.json entry fails, naming the (event,name) pair and the file", () => {
  const mutated = clone(hooksJsonJson);
  delete mutated.hooks.SessionStart[0].timeoutSec;
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /\[hooks\.json\] missing\/invalid timeout on \(SessionStart, daemon-up\)/);
});

// ─── AC-21: 0 / -1 / "30" each fail (hooks.json half) ──────────────────────
for (const badValue of [0, -1, "30"]) {
  it(`AC-21: hooks.json timeoutSec=${JSON.stringify(badValue)} is treated as undeclared`, () => {
    const mutated = clone(hooksJsonJson);
    mutated.hooks.SessionStart[0].timeoutSec = badValue;
    let threw = null;
    try {
      assertNoFailures(templateJson, mutated, implementedPairKeys);
    } catch (err) {
      threw = err;
    }
    assert.ok(threw, `timeoutSec=${JSON.stringify(badValue)} must fail the guard`);
    assert.match(threw.message, /missing\/invalid timeout on \(SessionStart, daemon-up\)/);
  });
}

// ─── AC-D26: 0 / -1 / "30" each fail (template.json half — previously
//     unreachable because the template was exempt) ─────────────────────────
for (const badValue of [0, -1, "30"]) {
  it(`AC-D26: template.json timeout=${JSON.stringify(badValue)} is treated as undeclared`, () => {
    const mutated = clone(templateJson);
    mutated.hooks.SessionStart[0].hooks[0].timeout = badValue;
    let threw = null;
    try {
      assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
    } catch (err) {
      threw = err;
    }
    assert.ok(threw, `template timeout=${JSON.stringify(badValue)} must fail the guard now that the template is no longer exempt`);
    assert.match(threw.message, /\[\.claude\/settings\.template\.json\] missing\/invalid timeout on \(SessionStart, daemon-up\)/);
  });
}

// ─── AC-22: move a wired PostToolUse entry's command under PreToolUse ──────
it("AC-22: moving a wired PostToolUse entry's command under PreToolUse fails, reporting both the containing key and the in-command event", () => {
  const mutated = clone(templateJson);
  const moved = mutated.hooks.PostToolUse.shift(); // remove cost-tally (PostToolUse) from its home
  mutated.hooks.PreToolUse.push(moved); // command text still says "hook PostToolUse cost-tally"
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /event mismatch for handler "cost-tally": containing key says "PreToolUse", command text says "PostToolUse"/);
});

// ─── AC-23: change only the powershell variant of one hooks.json entry ────
it("AC-23: changing only the powershell variant of a hooks.json entry fails, reporting that entry", () => {
  const mutated = clone(hooksJsonJson);
  mutated.hooks.SessionStart[0].powershell = mutated.hooks.SessionStart[0].powershell.replace(/daemon-up$/, "vendor-matrix");
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /bash\/powershell handler mismatch/);
  assert.match(threw.message, /daemon-up/);
  assert.match(threw.message, /vendor-matrix/);
});

// ─── AC-24: truncate a command, echo the raw string ───────────────────────
it("AC-24: truncating a command to omit the handler name fails and echoes the raw command string", () => {
  const mutated = clone(templateJson);

  // Phase L (#53): FIND a surviving command hook rather than naming one.
  //
  // This fixture used to mutate `hooks.PostToolUse[0].hooks[0]`, which Phase L
  // converted to an `mcp_tool` entry carrying no `command` at all. The
  // truncation then edited a field that does not exist, no unparseable command
  // was produced, and the test failed — loudly, which is the good outcome. Had
  // it instead been written to tolerate a missing command, it would have gone
  // green while testing nothing.
  //
  // Deriving the target means the next transport change relocates this fixture
  // automatically instead of quietly emptying it.
  let target = null;
  for (const [event, wrappers] of Object.entries(mutated.hooks)) {
    for (const wrapper of wrappers) {
      for (const h of wrapper.hooks ?? []) {
        if (typeof h.command === "string" && parseHookCommand(h.command)) {
          target = { event, entry: h, name: parseHookCommand(h.command).name };
          break;
        }
      }
      if (target) break;
    }
    if (target) break;
  }
  assert.ok(
    target,
    "no command hook remains in the template, so this falsification has nothing to truncate. If every " +
      "hook is now an mcp_tool, delete this test deliberately with a replacement rather than letting it " +
      "pass vacuously.",
  );

  const original = target.entry.command;
  assert.match(original, new RegExp(`hook ${target.event} ${target.name}$`));
  const truncated = original.slice(0, original.length - target.name.length).trim();
  target.entry.command = truncated;
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /unparseable hook-shaped command/);
  assert.ok(threw.message.includes(truncated), "raw truncated command string must be echoed verbatim");
});

// ─── AC-26: no failure message contains a home-directory path segment ─────
it("AC-26: none of the AC-18..AC-24 failure messages contain a home-directory path segment", () => {
  const home = homedir();
  const mutated1 = clone(templateJson);
  mutated1.hooks.SessionStart[0].hooks[0].command += ` ${join(home, "secret")}`;
  let threw = null;
  try {
    assertNoFailures(mutated1, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "the injected extra token must still break parsing (extra trailing token changes the extracted name)");
  if (home) assert.ok(!threw.message.includes(home), "home directory must never appear verbatim in a failure message");
});

// ─── AC-28 / AC-D27: no file is exempt from the timeout requirement ───────
it("AC-28: hooks.json is not exempt from the timeout requirement even if every entry loses its timeout", () => {
  const mutated = clone(hooksJsonJson);
  for (const arr of Object.values(mutated.hooks)) {
    for (const entry of arr) delete entry.timeoutSec;
  }
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "hooks.json must never be silently exempted from R2.14");
  assert.match(threw.message, /\[hooks\.json\] missing\/invalid timeout/);
});

it("AC-D27: buildFileReport takes no timeout-exemption parameter (arity 4), and the template is equally non-exempt", () => {
  assert.equal(buildFileReport.length, 4, "buildFileReport must take exactly 4 parameters now that isTimeoutExempt is gone");
  const mutated = clone(templateJson);
  for (const arr of Object.values(mutated.hooks)) {
    for (const wrapper of arr) {
      for (const h of wrapper.hooks) delete h.timeout;
    }
  }
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "settings.template.json must never be silently exempted from R2.14 any more");
  assert.match(threw.message, /\[\.claude\/settings\.template\.json\] missing\/invalid timeout/);
});

// ─── AC-D22 / AC-D23 / AC-D24 — replacing AC-29/29a/29b/29c: removing a
//     recall handler from ONE file is now a plain, unexcused failure ──────

it("AC-D22: removing eights-recall-project from settings.template.json (clone) fails as implemented-but-unwired, with no allowance to excuse it", () => {
  const mutated = clone(templateJson);
  const before = mutated.hooks.SessionStart.length;
  mutated.hooks.SessionStart = mutated.hooks.SessionStart.filter(
    w => !w.hooks.some(h => /eights-recall-project$/.test(h.command)),
  );
  assert.equal(mutated.hooks.SessionStart.length, before - 1, "fixture setup must actually remove exactly one wrapper");
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "an unwired implemented pair must fail unconditionally now that the pending-wiring allowance is gone");
  assert.match(threw.message, /\[\.claude\/settings\.template\.json\] implemented but unwired[\s\S]*\(SessionStart, eights-recall-project\)/);
});

it("AC-D23: the mirror — removing eights-recall-stage from hooks.json (clone) fails as implemented-but-unwired", () => {
  const mutated = clone(hooksJsonJson);
  const before = mutated.hooks.PreToolUse.length;
  mutated.hooks.PreToolUse = mutated.hooks.PreToolUse.filter(e => !/eights-recall-stage$/.test(e.bash));
  assert.equal(mutated.hooks.PreToolUse.length, before - 1, "fixture setup must actually remove exactly one entry");
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /\[hooks\.json\] implemented but unwired[\s\S]*\(PreToolUse, eights-recall-stage\)/);
});

it("AC-D24: the AC-D22 mutation produces exactly one diagnostic line mentioning eights-recall-project, attributed to the template only (no duplicate against hooks.json)", () => {
  const mutated = clone(templateJson);
  mutated.hooks.SessionStart = mutated.hooks.SessionStart.filter(
    w => !w.hooks.some(h => /eights-recall-project$/.test(h.command)),
  );
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  const matchingLines = threw.message.split("\n").filter(l => l.includes("eights-recall-project"));
  assert.equal(matchingLines.length, 1, `expected exactly one line naming eights-recall-project, got ${matchingLines.length}:\n${matchingLines.join("\n")}`);
  assert.match(matchingLines[0], /^\[\.claude\/settings\.template\.json\]/, "the sole diagnostic line must be attributed to the template");
});

// ─── AC-D25 — replacing AC-30: an undeclared template timeout is a plain,
//     unexcused failure ────────────────────────────────────────────────────
it("AC-D25: deleting timeout from a template.json entry fails, naming the pair, with no exemption to excuse it", () => {
  const mutated = clone(templateJson);
  delete mutated.hooks.SessionStart[0].hooks[0].timeout;
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "a template.json entry missing a timeout must fail now that the pending-timeout-exemption allowance is gone");
  assert.match(threw.message, /\[\.claude\/settings\.template\.json\] missing\/invalid timeout on \(SessionStart, daemon-up\)/);
});

// ─── AC-D28 — replacing AC-32: allowance-free restatement, exact-match only
it("AC-D28: a synthetic fourth eights-recall-* handler that is implemented-but-unwired fails (no prefix/wildcard excusal exists to reintroduce)", () => {
  const syntheticImplemented = new Set(implementedPairKeys);
  syntheticImplemented.add(pairKey("SessionStart", "eights-recall-session"));
  let threw = null;
  try {
    assertNoFailures(templateJson, hooksJsonJson, syntheticImplemented);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "a fourth eights-recall-* handler must fail — there is no allowance of any shape left to absorb it");
  assert.match(threw.message, /implemented but unwired[\s\S]*eights-recall-session/);
});

// ─── AC-D29 — replacing AC-31: wired-but-unimplemented fails unconditionally
it("AC-D29: a wired entry naming a handler absent from HANDLERS fails unconditionally, even under a name that collides with a recall handler", () => {
  const mutated = clone(hooksJsonJson);
  // Wire "eights-recall-project" under PostToolUse — the NAME collides with a
  // real implemented handler, but the PAIR (PostToolUse, eights-recall-project)
  // is not implemented under any event pairing.
  mutated.hooks.PostToolUse.push({
    type: "command",
    bash: 'node "daemon/dist/index.js" hook PostToolUse eights-recall-project',
    powershell: 'node "daemon/dist/index.js" hook PostToolUse eights-recall-project',
    timeoutSec: 30,
  });
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "no allowance may excuse a wired-but-unimplemented pair, regardless of name collision");
  assert.match(threw.message, /\[hooks\.json\] wired but unimplemented[\s\S]*PostToolUse, eights-recall-project/);
});

// ─── AC-D30 — every wired entry in both files declares a positive finite
//     numeric timeout, asserted positively (not merely "the guard didn't
//     complain") ────────────────────────────────────────────────────────────
it("AC-D30: every wired entry in both real files declares a positive finite numeric timeout", () => {
  const templateReduced = reduceTemplateEntries(extractTemplateEntries(templateJson));
  const hooksReduced = reduceHooksJsonEntries(extractHooksJsonEntries(hooksJsonJson));
  assert.ok(templateReduced.pairs.size > 0, "sanity: the template must have wired at least one pair");
  assert.ok(hooksReduced.pairs.size > 0, "sanity: hooks.json must have wired at least one pair");
  assert.deepEqual(templateReduced.missingTimeout, [], "every template.json entry must declare a valid timeout");
  assert.deepEqual(hooksReduced.missingTimeout, [], "every hooks.json entry must declare a valid timeoutSec");
});

// ─── AC-D31 — template `timeout` equals hooks.json `timeoutSec` for every
//     (event, name) pair ──────────────────────────────────────────────────
/**
 * Timeouts declared in the template, for COMMAND hooks only.
 *
 * Phase L (#53): `timeout` is a command-hook field. The 23 converted
 * `mcp_tool` entries declare none — correctly, since the field has no meaning
 * on that shape — so they are excluded here rather than given a stand-in
 * value. The exclusion is narrow and asserted from the other side too: a
 * separate test requires every mcp_tool entry to carry no `timeout` and no
 * `async`, so "absent because it is an mcp_tool" and "absent because someone
 * dropped it" stay distinguishable outcomes.
 */
function templateTimeoutMap(json) {
  const out = new Map();
  for (const e of extractTemplateEntries(json)) {
    if (e.parsed && e.transport === "command") out.set(pairKey(e.containingEvent, e.parsed.name), e.timeout);
  }
  return out;
}
function hooksJsonTimeoutMap(json) {
  const out = new Map();
  for (const e of extractHooksJsonEntries(json)) {
    if (e.bashParsed) out.set(pairKey(e.containingEvent, e.bashParsed.name), e.timeoutSec);
  }
  return out;
}
function findTimeoutParityMismatches(templateJsonArg, hooksJsonJsonArg) {
  const t = templateTimeoutMap(templateJsonArg);
  const h = hooksJsonTimeoutMap(hooksJsonJsonArg);
  const mismatches = [];
  for (const [key, tv] of t) {
    if (h.has(key) && h.get(key) !== tv) {
      mismatches.push(`${key}: template=${JSON.stringify(tv)} hooks.json=${JSON.stringify(h.get(key))}`);
    }
  }
  return mismatches;
}

it("AC-D31: template timeout equals hooks.json timeoutSec for every (event,name) pair in the real files", () => {
  const mismatches = findTimeoutParityMismatches(templateJson, hooksJsonJson);
  assert.deepEqual(mismatches, [], `timeout/timeoutSec parity mismatch: ${mismatches.join("; ")}`);
});

it("AC-D31 mutation: desynchronizing one pair's template timeout from its hooks.json timeoutSec is caught", () => {
  const mutated = clone(templateJson);
  mutated.hooks.SessionStart[0].hooks[0].timeout = 45; // daemon-up: template=30, hooks.json=30 -> now mismatched
  const mismatches = findTimeoutParityMismatches(mutated, hooksJsonJson);
  assert.ok(mismatches.length >= 1, "a desynchronized timeout pair must be reported");
  assert.match(mismatches.join("; "), /SessionStart daemon-up/);
});

// ─── AC-D32 — per-class timeout values, declared once, enforced everywhere
const TIMEOUT_CLASS = {
  // BLOCKING (10) + RECOVERY (3) = 13, timeout 30 — §3.2, unchanged from baseline.
  "SessionStart daemon-up": 30,
  "SessionStart vendor-matrix": 30,
  "PreToolUse block-destructive-shell": 30,
  "PreToolUse enforce-active-run": 30,
  "PreToolUse enforce-vendor-matrix": 30,
  "PreToolUse enforce-sandbox-policy": 30,
  "PreToolUse enforce-no-secrets": 30,
  "PreToolUse enforce-validator-gate": 30,
  "PreToolUse enforce-rfc2119-language": 30,
  "Stop decision-log-required": 30,
  "PostToolUse record-attempt": 30,
  "PostToolUse hash-artifact": 30,
  "PostToolUse update-master-plan": 30,
  // INFORMATIONAL (16), timeout 20 — a documented deviation from the spec's
  // derived 15 (driver-verified): 20 clears the 14 000 ms daemon-side
  // eights-recall bound (ECOSYSTEM_PROBE_TIMEOUT_MS x2 + ECOSYSTEM_CALL_TIMEOUT_MS)
  // with more headroom than 15 gave. Do not hardcode 15 here.
  "SessionStart cli-version-pin": 20,
  "SessionStart master-plan-load": 20,
  "SessionStart surfaced-runs": 20,
  "SessionStart eights-recall-project": 20,
  "PreToolUse eights-recall-stage": 20,
  "PostToolUse cost-tally": 20,
  "PostToolUse taxonomy-coverage-update": 20,
  "PostToolUse loop-ceiling-tally": 20,
  "PostToolUse verdict-rubric-coverage": 20,
  "UserPromptSubmit taxonomy-nudge": 20,
  "UserPromptSubmit team-suggester": 20,
  "UserPromptSubmit risk-flag": 20,
  "UserPromptSubmit surfaced-run-reminder": 20,
  "UserPromptSubmit profile-aware-nudge": 20,
  "UserPromptSubmit eights-recall-request": 20,
  "Stop summary-format-check": 20,
  // RECOVERY (Phase H, GitHub #49): both handlers write a ledger row in
  // direct response to a failure (a vendor-CLI tool failure, an API-killed
  // turn) -- same consequence-of-kill class as the other RECOVERY entries
  // above, so 30 not 20.
  "PostToolUseFailure record-execution-failure": 30,
  "StopFailure surface-api-killed-run": 30,
  // INFORMATIONAL (Phase H): detectors/observers with no gating role.
  // session-orphan-sweep's 20 additionally satisfies R11's declared >=20
  // floor against the documented SessionEnd budget (1.5s shared, raised to
  // match a longer per-hook timeout, up to 60s).
  "FileChanged constitution-drift-detect": 20,
  "PreCompact run-context-save": 20,
  "PostCompact run-context-reinject": 20,
  "SessionEnd session-orphan-sweep": 20,
  "SubagentStart subagent-dispatch-record": 20,
  "SubagentStop subagent-stop-observe": 20,
};

function findClassMismatches(templateJsonArg, hooksJsonJsonArg) {
  const t = templateTimeoutMap(templateJsonArg);
  const h = hooksJsonTimeoutMap(hooksJsonJsonArg);
  const mismatches = [];
  for (const [key, expected] of Object.entries(TIMEOUT_CLASS)) {
    if (t.has(key) && t.get(key) !== expected) mismatches.push(`[template] ${key}: expected ${expected}, got ${JSON.stringify(t.get(key))}`);
    if (h.has(key) && h.get(key) !== expected) mismatches.push(`[hooks.json] ${key}: expected ${expected}, got ${JSON.stringify(h.get(key))}`);
  }
  return mismatches;
}

it("AC-D32: the declared class->value map covers exactly the implemented inventory (derived, not hardcoded)", () => {
  assert.equal(
    Object.keys(TIMEOUT_CLASS).length,
    implementedPairKeys.size,
    "TIMEOUT_CLASS must have exactly one entry per implemented (event,name) pair",
  );
  for (const key of implementedPairKeys) {
    assert.ok(Object.prototype.hasOwnProperty.call(TIMEOUT_CLASS, key), `TIMEOUT_CLASS is missing an entry for ${key}`);
  }
});

it("AC-D32: every wired hook's timeout equals its declared class value in both real files", () => {
  const mismatches = findClassMismatches(templateJson, hooksJsonJson);
  assert.deepEqual(mismatches, [], `class/value mismatch: ${mismatches.join("; ")}`);
});

it("AC-D32 mutation: moving one hook's timeout off its class value is caught", () => {
  const mutated = clone(templateJson);
  mutated.hooks.SessionStart[0].hooks[0].timeout = 25; // daemon-up is class BLOCKING=30
  const mismatches = findClassMismatches(mutated, hooksJsonJson);
  assert.ok(mismatches.some(m => m.includes("SessionStart daemon-up") && m.includes("expected 30")), "an off-class timeout must be reported");
});

// ─── AC-D33 — statusMessage on the two blocking write-guards ──────────────
// Q8 is resolved for this run: Copilot's hooks.json entries carry no
// `statusMessage` (deliberate — Copilot support unverified), so the
// hooks.json half of R3.1/AC-D33 is scoped out here per R8.2, and this
// suite instead positively asserts hooks.json's absence so a stray
// hooks.json statusMessage does not silently diverge from that scoping
// decision without review.
const STATUS_MESSAGES = {
  "enforce-no-secrets": "pp: scanning this write for hardcoded credentials...",
  "enforce-validator-gate": "pp: checking the latest verdict before allowing this edit...",
};
const OUTCOME_WORDS = /\b(refuse[sd]?|block(ed)?|den(y|ied)|fail(ed)?)\b/i;

function findStatusMessageDefects(templateJsonArg) {
  const defects = [];
  const entries = extractTemplateEntries(templateJsonArg);
  for (const [name, expected] of Object.entries(STATUS_MESSAGES)) {
    const entry = entries.find(e => e.parsed && e.parsed.name === name);
    if (!entry) {
      defects.push(`${name}: not found in template`);
      continue;
    }
    if (typeof entry.statusMessage !== "string" || entry.statusMessage.length === 0) {
      defects.push(`${name}: statusMessage missing or empty`);
      continue;
    }
    if (entry.statusMessage.length > 80) {
      defects.push(`${name}: statusMessage exceeds 80 characters`);
    }
    if (entry.statusMessage !== expected) {
      defects.push(`${name}: statusMessage does not match the required literal`);
    }
    if (OUTCOME_WORDS.test(entry.statusMessage)) {
      defects.push(`${name}: statusMessage contains a banned outcome word`);
    }
  }
  return defects;
}

it("AC-D33: statusMessage on enforce-no-secrets and enforce-validator-gate is present, <=80 chars, matches the R3.3 literal, and is free of outcome words (template)", () => {
  const defects = findStatusMessageDefects(templateJson);
  assert.deepEqual(defects, [], `statusMessage defects: ${defects.join("; ")}`);
});

it("AC-D33: hooks.json carries no statusMessage on either write-guard (Q8 — Copilot support unverified, scoped out per R8.2)", () => {
  const entries = extractHooksJsonEntries(hooksJsonJson);
  for (const name of Object.keys(STATUS_MESSAGES)) {
    const entry = entries.find(e => e.bashParsed && e.bashParsed.name === name);
    assert.ok(entry, `${name} must be wired in hooks.json`);
    assert.equal(entry.statusMessage, undefined, `${name} must not declare statusMessage in hooks.json while Q8 is unresolved`);
  }
});

it("AC-D33 mutation: rewriting a statusMessage to outcome-shaped copy is caught", () => {
  const mutated = clone(templateJson);
  const entry = mutated.hooks.PreToolUse.find(w => w.hooks.some(h => /enforce-no-secrets$/.test(h.command)));
  entry.hooks[0].statusMessage = "pp: refuses the write if credentials are found";
  const defects = findStatusMessageDefects(mutated);
  assert.ok(defects.some(d => d.includes("enforce-no-secrets") && d.includes("outcome word")), "an outcome-shaped statusMessage must be caught");
});

// ─── AC-D34 — no `if:` key anywhere, under any event, in either file ──────
function findIfKeyViolations(templateJsonArg, hooksJsonJsonArg) {
  const violations = [];
  for (const e of extractTemplateEntries(templateJsonArg)) {
    if (e.hasIf) violations.push(`[${TEMPLATE_LABEL}] (${e.containingEvent}, ${e.parsed ? e.parsed.name : e.command}) declares an "if:" key`);
  }
  for (const e of extractHooksJsonEntries(hooksJsonJsonArg)) {
    if (e.hasIf) violations.push(`[${HOOKS_JSON_LABEL}] (${e.containingEvent}, ${e.bashParsed ? e.bashParsed.name : e.bash}) declares an "if:" key`);
  }
  return violations;
}

it("AC-D34: no entry in either real file, under any event, declares an if: key", () => {
  const violations = findIfKeyViolations(templateJson, hooksJsonJson);
  assert.deepEqual(violations, [], `if: key violations: ${violations.join("; ")}`);
});

it("AC-D34 mutation: adding an if: key to a clone of either file is caught", () => {
  const mutatedTemplate = clone(templateJson);
  mutatedTemplate.hooks.SessionStart[0].hooks[0].if = "some.predicate";
  const templateViolations = findIfKeyViolations(mutatedTemplate, hooksJsonJson);
  assert.ok(templateViolations.length >= 1, "an injected if: key in the template must be caught");

  const mutatedHooksJson = clone(hooksJsonJson);
  mutatedHooksJson.hooks.SessionStart[0].if = "some.predicate";
  const hooksViolations = findIfKeyViolations(templateJson, mutatedHooksJson);
  assert.ok(hooksViolations.length >= 1, "an injected if: key in hooks.json must be caught");
});

// ─── AC-34 — this change touches neither settings file ────────────────────
// All mutation checks above operate on JSON.parse(JSON.stringify(...)) deep
// clones (see `clone()`), never on TEMPLATE_PATH/HOOKS_JSON_PATH themselves.
// Prove it directly: the bytes on disk for both real files, read again now
// that every mutation-check has run, are byte-for-byte identical to what was
// loaded at the top of this file.
it("AC-34: the real settings files on disk are byte-for-byte unchanged after every mutation check has run", () => {
  const templateAfter = readFileSync(TEMPLATE_PATH, "utf8");
  const hooksJsonAfter = readFileSync(HOOKS_JSON_PATH, "utf8");
  assert.equal(templateAfter, TEMPLATE_RAW, "settings.template.json must be byte-for-byte unchanged on disk");
  assert.equal(hooksJsonAfter, HOOKS_JSON_RAW, "hooks.json must be byte-for-byte unchanged on disk");
});

// ─── Summary ────────────────────────────────────────────────────────────
console.log();
console.log(`${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
