// ─── Hook-inventory parity guard (GitHub #43, Phase A of epic #42) ─────────
//
// WHAT THIS GUARDS: daemon/src/hooks/dispatcher.ts implements 29 hook
// handlers (HANDLERS, keyed by event then name). Only 26 are wired in EACH
// of the two runtime settings files (.claude/settings.template.json for
// Claude Code, hooks.json at the repo root for the Copilot CLI plugin).
// Before this test existed, that 29-vs-26 drift was invisible: nothing
// compared the two inventories, so a handler could be fully implemented and
// reachable by name yet silently dead in both runtimes.
//
// AS OF 2026-09-05, the three pending/unwired handlers are:
//   - ("SessionStart",     "eights-recall-project")
//   - ("PreToolUse",       "eights-recall-stage")
//   - ("UserPromptSubmit", "eights-recall-request")
// These are TheEights episodic-recall hooks. Because none of the three is
// wired in EITHER settings file, TheEights episodic recall is consequently
// OFF in both the Claude Code and the Copilot runtime today.
//
// GitHub #46 (Phase D) is the issue that wires these three handlers and, per
// R2.26, deletes BOTH allowance lists below (PENDING_WIRING and
// PENDING_TIMEOUT_EXEMPT_FILES) once they stop being true.
//
// SOURCE-OF-TRUTH CONSTRAINT: this test reads ONLY
// `.claude/settings.template.json` (the tracked template) and MUST NOT read
// `.claude/settings.json` (git-ignored, generated by scripts/install-user.ps1,
// absent on a fresh clone / in CI).
//
// EXPORT CONSTRAINT: dispatcher.ts's HANDLERS constant is not exported. This
// test resolves the inventory via the side-effect-free `listHookHandlers()`
// export (dispatcher.ts:815), imported from `daemon/dist/`, per R2.5/R2.6 —
// no TypeScript source is parsed and no compiled-JS text is scraped.
//
// This file is fully self-contained (ANTI-STALL TEST RULE): no daemon, no
// MCP peer, no vendor CLI, no network, and no touch of
// ~/.pair-programmer/state.db (importing dispatcher.js triggers no hook and
// no DB access at module-load time; see the "import has no side effects"
// check below).
//
// MUTATION-CHECK STRATEGY: the acceptance criteria (AC-18..AC-32 in the
// spec) require confirming the guard goes RED under a battery of injected
// defects, with correctly-labelled messages. Rather than mutating the real
// settings files on disk (fragile, and risks leaving the repo dirty if a
// test aborts mid-run), this file mutates IN-MEMORY clones of the same
// parsed JSON structures and runs them through the exact same pure
// parse/compare/format functions used for the real-file assertions. A defect
// in the guard's logic is therefore caught identically whether it is
// exercised against the real tree or a synthetic fixture.

import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, isAbsolute, join } from "node:path";
import { homedir } from "node:os";
import assert from "node:assert/strict";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, "..", "..");
const DIST = join(__dirname, "..", "dist");

const TEMPLATE_PATH = join(REPO_ROOT, ".claude", "settings.template.json");
const HOOKS_JSON_PATH = join(REPO_ROOT, "hooks.json");
const TEMPLATE_LABEL = ".claude/settings.template.json";
const HOOKS_JSON_LABEL = "hooks.json";

let passed = 0;
let failed = 0;
function it(label, fn) {
  try {
    fn();
    passed++;
    console.log(`  pass  ${label}`);
  } catch (err) {
    failed++;
    console.error(`  FAIL  ${label}\n         ${err.message}`);
  }
}
async function itAsync(label, fn) {
  try {
    await fn();
    passed++;
    console.log(`  pass  ${label}`);
  } catch (err) {
    failed++;
    console.error(`  FAIL  ${label}\n         ${err.message}`);
  }
}

// ─── R2.23/R2.24/R2.25 — the two named, self-expiring allowances ──────────
//
// Both are literal, exhaustively-enumerated lists (R2.28: no prefix, no
// wildcard, no regex — a fourth eights-recall-* handler must NOT be
// silently absorbed). GitHub #46 (Phase D) removes both once the underlying
// gap it names is closed.

/** Pairs permitted to be implemented-but-unwired. Removed by #46 (Phase D) — the issue that wires all three into both runtime settings files. */
const PENDING_WIRING = [
  { event: "SessionStart", name: "eights-recall-project" },
  { event: "PreToolUse", name: "eights-recall-stage" },
  { event: "UserPromptSubmit", name: "eights-recall-request" },
];

/** Settings files permitted to have entries without a declared timeout. Removed by #46 (Phase D) once .claude/settings.template.json declares timeouts. */
const PENDING_TIMEOUT_EXEMPT_FILES = [TEMPLATE_LABEL];

function pairKey(event, name) {
  return `${event} ${name}`;
}
const PENDING_WIRING_KEYS = new Set(PENDING_WIRING.map(p => pairKey(p.event, p.name)));

// ─── AC-27: allowance declarations carry the tracking issue ───────────────
// A pure textual self-check: read this very file's source and confirm the
// two allowance declarations are each annotated with an inline comment
// naming #46. This is deliberately literal (not "does the constant exist")
// because R2.23 requires the comment, not just the list.
it("PENDING_WIRING and PENDING_TIMEOUT_EXEMPT_FILES declarations each carry a #46 comment", () => {
  const src = readFileSync(__filename, "utf8");
  const pwBlock = src.slice(src.indexOf("permitted to be implemented-but-unwired"), src.indexOf("const PENDING_WIRING ="));
  const ptBlock = src.slice(src.indexOf("permitted to have entries without a declared timeout"), src.indexOf("const PENDING_TIMEOUT_EXEMPT_FILES ="));
  assert.match(pwBlock, /#46/, "PENDING_WIRING's preceding comment must name #46");
  assert.match(ptBlock, /#46/, "PENDING_TIMEOUT_EXEMPT_FILES's preceding comment must name #46");
  assert.equal(PENDING_WIRING.length, 3, "PENDING_WIRING must contain exactly the three enumerated pairs");
  assert.deepEqual(
    PENDING_WIRING.map(p => `${p.event}/${p.name}`).sort(),
    ["PreToolUse/eights-recall-stage", "SessionStart/eights-recall-project", "UserPromptSubmit/eights-recall-request"],
    "PENDING_WIRING must contain exactly these three pairs and no others",
  );
  assert.deepEqual(PENDING_TIMEOUT_EXEMPT_FILES, [TEMPLATE_LABEL], "PENDING_TIMEOUT_EXEMPT_FILES must contain exactly .claude/settings.template.json");
});

// ─── R2.29 — header comment content check ─────────────────────────────────
it("header comment names the three pending handlers, the date, the recall-off statement, and #46", () => {
  const src = readFileSync(__filename, "utf8");
  const header = src.slice(0, src.indexOf("import { readFileSync }"));
  assert.match(header, /eights-recall-project/);
  assert.match(header, /eights-recall-stage/);
  assert.match(header, /eights-recall-request/);
  assert.match(header, /2026-09-05/);
  assert.match(header, /episodic recall is consequently[\s\S]*off in both/i);
  assert.match(header, /#46/);
});

// ─── Pure parsing helpers (shared by real-file checks and fixture-based
//     mutation checks) ────────────────────────────────────────────────────

/**
 * Extract {event, name} from a hook invocation command string of the shape
 * `... hook <Event> <name>`. Per R2.16: name is the FINAL whitespace token,
 * event is read from the command text itself (compared against the
 * containing key by the caller — this function does not know the key).
 * Returns null when the command does not carry a distinct name token after
 * "hook <Event>" (R2.18 — caller must treat null as a hard failure, not a
 * skip).
 */
function parseHookCommand(command) {
  if (typeof command !== "string" || !command.trim()) return null;
  const tokens = command.trim().split(/\s+/);
  const hookIdx = tokens.indexOf("hook");
  if (hookIdx === -1) return null;
  if (hookIdx + 2 >= tokens.length) return null; // no room for both <Event> and <name>
  const event = tokens[hookIdx + 1];
  const name = tokens[tokens.length - 1];
  if (hookIdx + 1 === tokens.length - 1) return null; // <Event> and <name> collapsed to one token
  if (!event || !name) return null;
  return { event, name };
}

function hasValidTimeout(v) {
  return typeof v === "number" && Number.isFinite(v) && v > 0;
}

/** Parse `.claude/settings.template.json`-shaped JSON into flat entries. */
function extractTemplateEntries(json) {
  const out = [];
  for (const [containingEvent, wrappers] of Object.entries(json.hooks ?? {})) {
    for (const wrapper of wrappers) {
      for (const h of wrapper.hooks ?? []) {
        out.push({
          containingEvent,
          command: h.command,
          parsed: parseHookCommand(h.command),
          timeout: h.timeout,
        });
      }
    }
  }
  return out;
}

/** Parse `hooks.json`-shaped JSON into flat entries (bash + powershell). */
function extractHooksJsonEntries(json) {
  const out = [];
  for (const [containingEvent, entries] of Object.entries(json.hooks ?? {})) {
    for (const entry of entries) {
      out.push({
        containingEvent,
        bash: entry.bash,
        powershell: entry.powershell,
        bashParsed: parseHookCommand(entry.bash),
        pwshParsed: parseHookCommand(entry.powershell),
        timeoutSec: entry.timeoutSec,
      });
    }
  }
  return out;
}

/**
 * Reduce template entries into: the (event,name) pair set, unparseable raw
 * commands (R2.18), event/key mismatches (R2.16), and entries missing a
 * valid timeout (R2.13/R2.15).
 */
function reduceTemplateEntries(entries) {
  const pairs = new Set();
  const unparseable = [];
  const eventMismatches = [];
  const missingTimeout = [];
  for (const e of entries) {
    if (!e.parsed) {
      unparseable.push(e.command);
      continue;
    }
    if (e.parsed.event !== e.containingEvent) {
      eventMismatches.push({ containingKey: e.containingEvent, commandEvent: e.parsed.event, name: e.parsed.name });
    }
    pairs.add(pairKey(e.containingEvent, e.parsed.name));
    if (!hasValidTimeout(e.timeout)) {
      missingTimeout.push({ event: e.containingEvent, name: e.parsed.name });
    }
  }
  return { pairs, unparseable, eventMismatches, missingTimeout };
}

/** Mirror of reduceTemplateEntries for hooks.json's bash/powershell schema. */
function reduceHooksJsonEntries(entries) {
  const pairs = new Set();
  const unparseable = [];
  const eventMismatches = [];
  const bashPwshMismatches = [];
  const missingTimeout = [];
  for (const e of entries) {
    if (!e.bashParsed || !e.pwshParsed) {
      unparseable.push(e.bash ?? e.powershell ?? "(no command)");
      continue;
    }
    if (e.bashParsed.event !== e.pwshParsed.event || e.bashParsed.name !== e.pwshParsed.name) {
      bashPwshMismatches.push({ bash: e.bash, powershell: e.powershell });
      continue;
    }
    if (e.bashParsed.event !== e.containingEvent) {
      eventMismatches.push({ containingKey: e.containingEvent, commandEvent: e.bashParsed.event, name: e.bashParsed.name });
    }
    pairs.add(pairKey(e.containingEvent, e.bashParsed.name));
    if (!hasValidTimeout(e.timeoutSec)) {
      missingTimeout.push({ event: e.containingEvent, name: e.bashParsed.name });
    }
  }
  return { pairs, unparseable, eventMismatches, bashPwshMismatches, missingTimeout };
}

/**
 * Compute the parity diagnosis for one settings file against the implemented
 * set, applying the PENDING_WIRING allowance PER FILE (R2.26b): a pending
 * pair suppresses an implemented-but-unwired failure only when genuinely
 * absent from wiredPairs. If the pair IS present in wiredPairs, that is
 * staleness (R2.26), reported separately — never silently absorbed and never
 * ALSO reported as an ordinary implemented-but-unwired failure (R2.26a/AC-29c).
 */
function diagnoseParity(implementedPairs, wiredPairs) {
  const implementedButUnwired = [];
  const staleAllowance = [];
  // Staleness: any PENDING_WIRING pair that IS wired in this file.
  for (const key of PENDING_WIRING_KEYS) {
    if (wiredPairs.has(key)) staleAllowance.push(key);
  }
  // True implemented-but-unwired: implemented, not wired here, AND not a
  // (still-valid, i.e. not stale) pending pair.
  for (const p of implementedPairs) {
    if (wiredPairs.has(p)) continue;
    if (PENDING_WIRING_KEYS.has(p)) continue; // excused (staleness reported separately if applicable)
    implementedButUnwired.push(p);
  }
  const wiredButUnimplemented = [...wiredPairs].filter(p => !implementedPairs.has(p));
  return { implementedButUnwired, wiredButUnimplemented, staleAllowance };
}

function unkey(key) {
  const [event, name] = key.split(" ");
  return { event, name };
}

function formatPairs(keys) {
  return keys.map(k => { const { event, name } = unkey(k); return `(${sanitize(event)}, ${sanitize(name)})`; }).join(", ");
}

/** R2.22: strip a home-dir prefix so failure messages never carry one. */
function sanitize(s) {
  const home = homedir();
  if (home && typeof s === "string" && s.includes(home)) return s.split(home).join("~");
  return s;
}

/**
 * Build the full diagnostic message for one file. Returns null when there is
 * nothing to report. This is the single source of failure-message text so
 * every mutation check exercises the exact same formatting code the real
 * assertion uses.
 */
function buildFileReport(fileLabel, implementedPairs, wiredPairs, reduced, isTimeoutExempt) {
  const { implementedButUnwired, wiredButUnimplemented, staleAllowance } = diagnoseParity(implementedPairs, wiredPairs);
  const lines = [];

  if (implementedButUnwired.length) {
    lines.push(`[${fileLabel}] implemented but unwired: ${formatPairs(implementedButUnwired)}`);
  }
  if (wiredButUnimplemented.length) {
    lines.push(`[${fileLabel}] wired but unimplemented: ${formatPairs(wiredButUnimplemented)}`);
  }
  if (staleAllowance.length) {
    for (const key of staleAllowance) {
      const { event, name } = unkey(key);
      lines.push(
        `[${fileLabel}] STALE ALLOWANCE: (${sanitize(event)}, ${sanitize(name)}) is listed in PENDING_WIRING but is now wired in ${fileLabel}. ` +
        `Delete this pair from PENDING_WIRING (GitHub #46 is done for this handler).`,
      );
    }
  }
  if (reduced.unparseable.length) {
    for (const raw of reduced.unparseable) {
      lines.push(`[${fileLabel}] unparseable hook-shaped command (no handler name extracted): ${sanitize(raw)}`);
    }
  }
  if (reduced.eventMismatches.length) {
    for (const m of reduced.eventMismatches) {
      lines.push(
        `[${fileLabel}] event mismatch for handler "${sanitize(m.name)}": containing key says "${sanitize(m.containingKey)}", ` +
        `command text says "${sanitize(m.commandEvent)}"`,
      );
    }
  }
  if (reduced.bashPwshMismatches && reduced.bashPwshMismatches.length) {
    for (const m of reduced.bashPwshMismatches) {
      lines.push(`[${fileLabel}] bash/powershell handler mismatch: bash="${sanitize(m.bash)}" powershell="${sanitize(m.powershell)}"`);
    }
  }
  if (!isTimeoutExempt && reduced.missingTimeout.length) {
    for (const m of reduced.missingTimeout) {
      lines.push(`[${fileLabel}] missing/invalid timeout on (${sanitize(m.event)}, ${sanitize(m.name)})`);
    }
  } else if (isTimeoutExempt && reduced.missingTimeout.length === 0) {
    lines.push(
      `[${fileLabel}] STALE ALLOWANCE: every entry in ${fileLabel} now declares a valid timeout. ` +
      `Delete ${fileLabel} from PENDING_TIMEOUT_EXEMPT_FILES (GitHub #46 is done).`,
    );
  }
  return lines;
}

function assertNoFailures(templateJson, hooksJsonJson, implementedPairs) {
  const templateEntries = extractTemplateEntries(templateJson);
  const hooksEntries = extractHooksJsonEntries(hooksJsonJson);
  const templateReduced = reduceTemplateEntries(templateEntries);
  const hooksReduced = reduceHooksJsonEntries(hooksEntries);

  const templateLines = buildFileReport(
    TEMPLATE_LABEL, implementedPairs, templateReduced.pairs, templateReduced,
    PENDING_TIMEOUT_EXEMPT_FILES.includes(TEMPLATE_LABEL),
  );
  const hooksLines = buildFileReport(
    HOOKS_JSON_LABEL, implementedPairs, hooksReduced.pairs, hooksReduced,
    PENDING_TIMEOUT_EXEMPT_FILES.includes(HOOKS_JSON_LABEL),
  );
  const all = [...templateLines, ...hooksLines];
  if (all.length) {
    throw new Error(`hook-inventory parity failures:\n${all.join("\n")}`);
  }
  return { templateReduced, hooksReduced };
}

// ─── Load real files + real implemented inventory ─────────────────────────

// Raw text is retained alongside the parsed form so AC-34 can assert
// byte-for-byte immutability rather than semantic equality — a mutation that
// round-trips through JSON.parse identically (reordered keys, changed
// whitespace) would slip past a deepEqual but is still an edit to a tracked file.
const TEMPLATE_RAW = readFileSync(TEMPLATE_PATH, "utf8");
const HOOKS_JSON_RAW = readFileSync(HOOKS_JSON_PATH, "utf8");
const templateJson = JSON.parse(TEMPLATE_RAW);
const hooksJsonJson = JSON.parse(HOOKS_JSON_RAW);

// R2.11: never read .claude/settings.json. Prose mentions of the excluded
// path (explaining WHY it is excluded) are fine; what must never appear is a
// quoted string literal path segment naming it as something this file reads.
it("this file never reads .claude/settings.json (only settings.template.json)", () => {
  const src = readFileSync(__filename, "utf8");
  const bareSettingsJsonLiteral = ["s", "ettings.json"].join("");
  const quoted = new RegExp(`["'\`]${bareSettingsJsonLiteral.replace(".", "\\.")}["'\`]`);
  assert.ok(!quoted.test(src),
    "no quoted bare-settings-file path-segment literal may appear (would indicate this file reads the git-ignored generated file)");
  assert.ok(TEMPLATE_PATH.endsWith("settings.template.json"), "TEMPLATE_PATH must resolve to the template, not the generated file");
});

let listHookHandlers;
await itAsync("dispatcher.js imports cleanly with no side effects (no hook run, no process.exit, no DB touch)", async () => {
  const before = Date.now();
  const mod = await import(pathToFileURL(join(DIST, "hooks", "dispatcher.js")).href);
  assert.equal(typeof mod.listHookHandlers, "function", "listHookHandlers must be exported");
  assert.ok(Date.now() - before < 5000, "import must be near-instant (no blocking I/O at module scope)");
  listHookHandlers = mod.listHookHandlers;
});

const EXPECTED_IMPLEMENTED = [
  ["SessionStart", "daemon-up"], ["SessionStart", "vendor-matrix"], ["SessionStart", "cli-version-pin"],
  ["SessionStart", "master-plan-load"], ["SessionStart", "surfaced-runs"], ["SessionStart", "eights-recall-project"],
  ["PreToolUse", "block-destructive-shell"], ["PreToolUse", "enforce-active-run"], ["PreToolUse", "enforce-vendor-matrix"],
  ["PreToolUse", "enforce-sandbox-policy"], ["PreToolUse", "enforce-no-secrets"], ["PreToolUse", "enforce-validator-gate"],
  ["PreToolUse", "enforce-rfc2119-language"], ["PreToolUse", "eights-recall-stage"],
  ["PostToolUse", "cost-tally"], ["PostToolUse", "record-attempt"], ["PostToolUse", "taxonomy-coverage-update"],
  ["PostToolUse", "hash-artifact"], ["PostToolUse", "loop-ceiling-tally"], ["PostToolUse", "verdict-rubric-coverage"],
  ["PostToolUse", "update-master-plan"],
  ["UserPromptSubmit", "taxonomy-nudge"], ["UserPromptSubmit", "team-suggester"], ["UserPromptSubmit", "risk-flag"],
  ["UserPromptSubmit", "surfaced-run-reminder"], ["UserPromptSubmit", "profile-aware-nudge"], ["UserPromptSubmit", "eights-recall-request"],
  ["Stop", "decision-log-required"], ["Stop", "summary-format-check"],
];

let implementedPairKeys;
it("listHookHandlers() returns exactly the 29 pairs enumerated in the spec (AC-15)", () => {
  const raw = listHookHandlers();
  assert.equal(raw.length, 29, `expected 29 implemented (event,name) pairs, got ${raw.length}`);
  const keys = new Set(raw.map(p => pairKey(p.event, p.name)));
  implementedPairKeys = keys;
  const expectedKeys = new Set(EXPECTED_IMPLEMENTED.map(([e, n]) => pairKey(e, n)));
  assert.deepEqual(
    [...keys].sort(),
    [...expectedKeys].sort(),
    "the exported inventory must match the enumeration in spec section 2.3 exactly, by event and by name",
  );
});

// ─── AC-12..AC-17, AC-27, AC-33, AC-34 — the real-tree assertion ──────────

it("hook inventory parity holds against the real repository tree (with the two named allowances)", () => {
  assertNoFailures(templateJson, hooksJsonJson, implementedPairKeys);
});

it("the test resolves both settings paths via import.meta.url, not process.cwd()", () => {
  // R2.12/AC-17. This assertion must stay FALSIFIABLE: an earlier revision
  // ended in `|| true`, which made the whole expression unconditionally true
  // and left the requirement unasserted. Recompute the paths from
  // import.meta.url and require the module-level constants to match exactly —
  // if someone rebases either constant onto process.cwd(), this diverges the
  // moment the suite is invoked from anywhere but the repo root.
  const fromUrl = dirname(fileURLToPath(import.meta.url));
  const expectedTemplate = join(fromUrl, "..", "..", ".claude", "settings.template.json");
  const expectedHooksJson = join(fromUrl, "..", "..", "hooks.json");

  assert.equal(TEMPLATE_PATH, expectedTemplate,
    "TEMPLATE_PATH must be derived from import.meta.url, not process.cwd()");
  assert.equal(HOOKS_JSON_PATH, expectedHooksJson,
    "HOOKS_JSON_PATH must be derived from import.meta.url, not process.cwd()");

  // Both must be absolute; a relative path would silently re-resolve per cwd.
  assert.ok(isAbsolute(TEMPLATE_PATH), "TEMPLATE_PATH must be absolute");
  assert.ok(isAbsolute(HOOKS_JSON_PATH), "HOOKS_JSON_PATH must be absolute");

  // And they must actually resolve to readable files from this cwd, whatever it is.
  assert.ok(readFileSync(TEMPLATE_PATH, "utf8").length > 0);
  assert.ok(readFileSync(HOOKS_JSON_PATH, "utf8").length > 0);
});

// ─── Deep-clone helper for fixture mutations ──────────────────────────────
function clone(obj) { return JSON.parse(JSON.stringify(obj)); }

// ─── AC-18: rename one wired template.json handler to a nonexistent name ──
it("AC-18: renaming a wired template.json handler to a nonexistent name fails, naming both directions", () => {
  const mutated = clone(templateJson);
  const entry = mutated.hooks.SessionStart[0].hooks[0];
  assert.match(entry.command, /daemon-up$/);
  entry.command = entry.command.replace(/daemon-up$/, "daemon-up-typo");
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "mutation must make the guard fail");
  assert.match(threw.message, /wired but unimplemented[\s\S]*daemon-up-typo/);
  assert.match(threw.message, /implemented but unwired[\s\S]*daemon-up/);
  // AC-25: message must name literal strings, not just integers.
  assert.match(threw.message, /daemon-up-typo/);
  // AC-20/21 not applicable here.
});

// ─── AC-19: same mutation applied to hooks.json ────────────────────────────
it("AC-19: the same rename mutation in hooks.json produces the same two labelled groups, attributed to hooks.json", () => {
  const mutated = clone(hooksJsonJson);
  const entry = mutated.hooks.SessionStart[0];
  entry.bash = entry.bash.replace(/daemon-up$/, "daemon-up-typo");
  entry.powershell = entry.powershell.replace(/daemon-up$/, "daemon-up-typo");
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /\[hooks\.json\] wired but unimplemented[\s\S]*daemon-up-typo/);
  assert.match(threw.message, /\[hooks\.json\] implemented but unwired[\s\S]*daemon-up/);
});

// ─── AC-20: remove timeoutSec from one hooks.json entry ────────────────────
it("AC-20: removing timeoutSec from a hooks.json entry fails, naming the (event,name) pair and the file", () => {
  const mutated = clone(hooksJsonJson);
  delete mutated.hooks.SessionStart[0].timeoutSec;
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /\[hooks\.json\] missing\/invalid timeout on \(SessionStart, daemon-up\)/);
});

// ─── AC-21: 0 / -1 / "30" each fail ────────────────────────────────────────
for (const badValue of [0, -1, "30"]) {
  it(`AC-21: hooks.json timeoutSec=${JSON.stringify(badValue)} is treated as undeclared`, () => {
    const mutated = clone(hooksJsonJson);
    mutated.hooks.SessionStart[0].timeoutSec = badValue;
    let threw = null;
    try {
      assertNoFailures(templateJson, mutated, implementedPairKeys);
    } catch (err) {
      threw = err;
    }
    assert.ok(threw, `timeoutSec=${JSON.stringify(badValue)} must fail the guard`);
    assert.match(threw.message, /missing\/invalid timeout on \(SessionStart, daemon-up\)/);
  });
}

// ─── AC-22: move a wired PostToolUse entry's command under PreToolUse ──────
it("AC-22: moving a wired PostToolUse entry's command under PreToolUse fails, reporting both the containing key and the in-command event", () => {
  const mutated = clone(templateJson);
  const moved = mutated.hooks.PostToolUse.shift(); // remove cost-tally (PostToolUse) from its home
  mutated.hooks.PreToolUse.push(moved); // command text still says "hook PostToolUse cost-tally"
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /event mismatch for handler "cost-tally": containing key says "PreToolUse", command text says "PostToolUse"/);
});

// ─── AC-23: change only the powershell variant of one hooks.json entry ────
it("AC-23: changing only the powershell variant of a hooks.json entry fails, reporting that entry", () => {
  const mutated = clone(hooksJsonJson);
  mutated.hooks.SessionStart[0].powershell = mutated.hooks.SessionStart[0].powershell.replace(/daemon-up$/, "vendor-matrix");
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /bash\/powershell handler mismatch/);
  assert.match(threw.message, /daemon-up/);
  assert.match(threw.message, /vendor-matrix/);
});

// ─── AC-24: truncate a command, echo the raw string ───────────────────────
it("AC-24: truncating a command to omit the handler name fails and echoes the raw command string", () => {
  const mutated = clone(templateJson);
  const original = mutated.hooks.PostToolUse[0].hooks[0].command;
  assert.match(original, /hook PostToolUse cost-tally$/);
  const truncated = original.replace(/cost-tally$/, "").trim();
  mutated.hooks.PostToolUse[0].hooks[0].command = truncated;
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /unparseable hook-shaped command/);
  assert.ok(threw.message.includes(truncated), "raw truncated command string must be echoed verbatim");
});

// ─── AC-26: no failure message contains a home-directory path segment ─────
it("AC-26: none of the AC-18..AC-24 failure messages contain a home-directory path segment", () => {
  const home = homedir();
  const mutated1 = clone(templateJson);
  mutated1.hooks.SessionStart[0].hooks[0].command += ` ${join(home, "secret")}`;
  let threw = null;
  try {
    assertNoFailures(mutated1, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "the injected extra token must still break parsing (extra trailing token changes the extracted name)");
  if (home) assert.ok(!threw.message.includes(home), "home directory must never appear verbatim in a failure message");
});

// ─── AC-28: hooks.json is never timeout-exempt, even template-shaped ──────
it("AC-28: hooks.json is not exempt from the timeout requirement even if every entry loses its timeout", () => {
  const mutated = clone(hooksJsonJson);
  for (const arr of Object.values(mutated.hooks)) {
    for (const entry of arr) delete entry.timeoutSec;
  }
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "hooks.json must never be silently exempted from R2.14");
  assert.match(threw.message, /\[hooks\.json\] missing\/invalid timeout/);
});

// ─── AC-29 / AC-29a / AC-29b / AC-29c — self-expiring PENDING_WIRING ──────

function wireEightsRecallProjectIntoTemplate(json) {
  const mutated = clone(json);
  mutated.hooks.SessionStart.push({
    hooks: [{ type: "command", command: 'node "__PP_DAEMON__" hook SessionStart eights-recall-project' }],
  });
  return mutated;
}
function wireEightsRecallProjectIntoHooksJson(json, { withTimeout = true } = {}) {
  const mutated = clone(json);
  const entry = {
    type: "command",
    bash: 'node "daemon/dist/index.js" hook SessionStart eights-recall-project',
    powershell: 'node "daemon/dist/index.js" hook SessionStart eights-recall-project',
  };
  if (withTimeout) entry.timeoutSec = 30;
  mutated.hooks.SessionStart.push(entry);
  return mutated;
}

it("AC-29: wiring eights-recall-project into BOTH files fails with a staleness message naming the pair", () => {
  const mutatedTemplate = wireEightsRecallProjectIntoTemplate(templateJson);
  const mutatedHooksJson = wireEightsRecallProjectIntoHooksJson(hooksJsonJson);
  let threw = null;
  try {
    assertNoFailures(mutatedTemplate, mutatedHooksJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(threw.message, /STALE ALLOWANCE: \(SessionStart, eights-recall-project\) is listed in PENDING_WIRING/);
  assert.match(threw.message, /Delete this pair from PENDING_WIRING/);
});

it("AC-29a: wiring eights-recall-project into settings.template.json ONLY must go red, naming that pair and that file, instructing removal", () => {
  const mutatedTemplate = wireEightsRecallProjectIntoTemplate(templateJson);
  let threw = null;
  try {
    assertNoFailures(mutatedTemplate, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "a one-file-only wiring MUST turn the suite red under the either/not-both rule (R2.26a)");
  assert.match(
    threw.message,
    /\[\.claude\/settings\.template\.json\] STALE ALLOWANCE: \(SessionStart, eights-recall-project\) is listed in PENDING_WIRING but is now wired in \.claude\/settings\.template\.json\. Delete this pair from PENDING_WIRING/,
  );
});

it("AC-29b: the mirror — wiring eights-recall-stage into hooks.json ONLY must go red, naming that pair and hooks.json", () => {
  const mutatedHooksJson = clone(hooksJsonJson);
  mutatedHooksJson.hooks.PreToolUse.push({
    type: "command",
    bash: 'node "daemon/dist/index.js" hook PreToolUse eights-recall-stage',
    powershell: 'node "daemon/dist/index.js" hook PreToolUse eights-recall-stage',
    timeoutSec: 30,
  });
  let threw = null;
  try {
    assertNoFailures(templateJson, mutatedHooksJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  assert.match(
    threw.message,
    /\[hooks\.json\] STALE ALLOWANCE: \(PreToolUse, eights-recall-stage\) is listed in PENDING_WIRING but is now wired in hooks\.json\. Delete this pair from PENDING_WIRING/,
  );
});

it("AC-29c: the AC-29a mutation does NOT also report the pair as an unexplained implemented-but-unwired failure against hooks.json", () => {
  const mutatedTemplate = wireEightsRecallProjectIntoTemplate(templateJson);
  let threw = null;
  try {
    assertNoFailures(mutatedTemplate, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw);
  // The ONLY diagnosis for this pair must be the stale-allowance message on
  // the template file. It must NOT ALSO appear as a plain "implemented but
  // unwired" line attributed to hooks.json (that would be two contradictory
  // messages for one condition).
  assert.ok(
    !/\[hooks\.json\] implemented but unwired[\s\S]*eights-recall-project/.test(threw.message),
    "the pair's absence from hooks.json must stay silently excused, not re-reported as a separate failure",
  );
});

// ─── AC-30 — PENDING_TIMEOUT_EXEMPT_FILES self-expiry ─────────────────────
it("AC-30: adding a valid timeout to every template.json entry fails, instructing removal from PENDING_TIMEOUT_EXEMPT_FILES", () => {
  const mutated = clone(templateJson);
  for (const arr of Object.values(mutated.hooks)) {
    for (const wrapper of arr) {
      for (const h of wrapper.hooks) h.timeout = 30;
    }
  }
  let threw = null;
  try {
    assertNoFailures(mutated, hooksJsonJson, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "a fully-timed-out template.json must expire its own exemption");
  assert.match(
    threw.message,
    /\[\.claude\/settings\.template\.json\] STALE ALLOWANCE: every entry in \.claude\/settings\.template\.json now declares a valid timeout\. Delete \.claude\/settings\.template\.json from PENDING_TIMEOUT_EXEMPT_FILES/,
  );
});

// ─── AC-31 — wired-but-unimplemented has NO allowance, even name-colliding ─
it("AC-31: a wired entry naming a handler absent from HANDLERS fails unconditionally, even when the name matches a PENDING_WIRING entry under the wrong event", () => {
  const mutated = clone(hooksJsonJson);
  // Wire "eights-recall-project" under PostToolUse — the NAME matches a
  // PENDING_WIRING entry, but the PAIR (PostToolUse, eights-recall-project)
  // is not implemented under any event pairing, and PENDING_WIRING excuses
  // implemented-but-unwired only, never wired-but-unimplemented (R2.27).
  mutated.hooks.PostToolUse.push({
    type: "command",
    bash: 'node "daemon/dist/index.js" hook PostToolUse eights-recall-project',
    powershell: 'node "daemon/dist/index.js" hook PostToolUse eights-recall-project',
    timeoutSec: 30,
  });
  let threw = null;
  try {
    assertNoFailures(templateJson, mutated, implementedPairKeys);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "no allowance may excuse a wired-but-unimplemented pair, regardless of name collision");
  assert.match(threw.message, /\[hooks\.json\] wired but unimplemented[\s\S]*PostToolUse, eights-recall-project/);
});

// ─── AC-32 — allowance is exact-match, not prefix-based ───────────────────
it("AC-32: a fourth eights-recall-* handler that is implemented-but-unwired is NOT absorbed by the PENDING_WIRING allowance (exact-match only)", () => {
  const syntheticImplemented = new Set(implementedPairKeys);
  syntheticImplemented.add(pairKey("SessionStart", "eights-recall-session"));
  let threw = null;
  try {
    assertNoFailures(templateJson, hooksJsonJson, syntheticImplemented);
  } catch (err) {
    threw = err;
  }
  assert.ok(threw, "a fourth eights-recall-* handler must NOT be silently excused by a prefix/wildcard reading of PENDING_WIRING");
  assert.match(threw.message, /implemented but unwired[\s\S]*eights-recall-session/);
});

// ─── AC-34 — this change touches neither settings file ────────────────────
// All mutation checks above operate on JSON.parse(JSON.stringify(...)) deep
// clones (see `clone()`), never on TEMPLATE_PATH/HOOKS_JSON_PATH themselves.
// Prove it directly: the bytes on disk for both real files, read again now
// that every mutation-check has run, are byte-for-byte identical to what was
// loaded at the top of this file.
it("AC-34: the real settings files on disk are byte-for-byte unchanged after every mutation check has run", () => {
  const templateAfter = readFileSync(TEMPLATE_PATH, "utf8");
  const hooksJsonAfter = readFileSync(HOOKS_JSON_PATH, "utf8");
  assert.equal(templateAfter, TEMPLATE_RAW, "settings.template.json must be byte-for-byte unchanged on disk");
  assert.equal(hooksJsonAfter, HOOKS_JSON_RAW, "hooks.json must be byte-for-byte unchanged on disk");
});

// ─── Summary ────────────────────────────────────────────────────────────
console.log();
console.log(`${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
