/**
 * Regression guard for the Copilot-mirror comment-stripping defect.
 *
 * scripts/sync-copilot-assets.mjs rebuilds Copilot frontmatter from a whitelist
 * of keys instead of copying the .claude source frontmatter, so YAML comments
 * were silently dropped. The casualty was the rationale above
 * `copilot-model: gpt-5.4` in .claude/agents/pair-programmer-orchestrator.md —
 * a warning that the Copilot CLI catalog is NOT the `codex exec` catalog and
 * that sweeping the pin with the codex pins reproduces AGY-MODEL-ID-STALE.
 * Anyone reading (or sweeping) the mirror never saw it, and editing the mirror
 * was futile because the next sync overwrote it.
 *
 * These tests assert on the CHECKED-IN mirror, so they fail if someone
 * regenerates without the preservation step.
 *
 * Self-contained: pure file reads, no daemon, no dist import.
 */

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFileSync, existsSync } from "node:fs";
import assert from "node:assert/strict";
import { test, describe } from "node:test";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");

const SOURCE = join(ROOT, ".claude", "agents", "pair-programmer-orchestrator.md");
const MIRROR = join(ROOT, ".github", "agents", "pair-programmer-orchestrator.agent.md");

describe("sync-copilot-assets preserves frontmatter comments", () => {
  test("the .claude source still carries the copilot-model rationale comment", () => {
    assert.ok(existsSync(SOURCE), `${SOURCE} must exist`);
    const src = readFileSync(SOURCE, "utf8");
    assert.match(
      src,
      /^#.*copilot-model is deliberately NOT swept with the codex pins/m,
      "source rationale comment removed — if this pin is now safe to sweep, say so explicitly",
    );
  });

  test("the generated .github mirror carries that rationale in its body", () => {
    assert.ok(existsSync(MIRROR), `${MIRROR} must exist — run node scripts/sync-copilot-assets.mjs`);
    const mirror = readFileSync(MIRROR, "utf8");
    assert.match(
      mirror,
      /copilot-model is deliberately NOT swept with the codex pins/,
      "mirror lost the rationale — sync-copilot-assets.mjs is stripping frontmatter comments again",
    );
    assert.match(
      mirror,
      /AGY-MODEL-ID-STALE/,
      "the failure-mode reference must survive into the mirror, not just a truncated first line",
    );
  });

  test("the rationale is emitted as an HTML comment in the body, not inside the frontmatter", () => {
    const mirror = readFileSync(MIRROR, "utf8").replace(/\r\n/g, "\n");
    assert.ok(mirror.startsWith("---\n"), "mirror must start with a frontmatter fence");
    const end = mirror.indexOf("\n---\n", 4);
    assert.ok(end > 0, "mirror must have a closing frontmatter fence");
    const frontmatter = mirror.slice(4, end);
    const body = mirror.slice(end + 5);

    assert.ok(
      !/copilot-model is deliberately/.test(frontmatter),
      "rationale must NOT be injected into the schema-validated Copilot frontmatter",
    );
    assert.match(body, /<!--[\s\S]*copilot-model is deliberately[\s\S]*-->/,
      "rationale must appear inside an HTML comment in the body");
    // The banner must come first so a reader hits "do not edit this file" before
    // the preserved rationale.
    const bannerIdx = body.indexOf("Generated from");
    const rationaleIdx = body.indexOf("copilot-model is deliberately");
    assert.ok(bannerIdx >= 0 && bannerIdx < rationaleIdx,
      "generated-from banner must precede the preserved rationale");
  });

  test("the preserved payload cannot terminate its own HTML comment", () => {
    const mirror = readFileSync(MIRROR, "utf8").replace(/\r\n/g, "\n");
    const block = /<!--\s*Frontmatter rationale preserved[\s\S]*?-->/.exec(mirror);
    assert.ok(block, "preserved-comment block must exist in the mirror");
    const inner = block[0].slice(4, -3);
    assert.ok(
      !inner.includes("--"),
      "a literal '--' inside the payload would close the HTML comment early; it must be neutralised",
    );
  });

  test("the mirror still pins copilot model gpt-5.4", () => {
    const mirror = readFileSync(MIRROR, "utf8");
    assert.match(mirror, /^model:\s*"?gpt-5\.4"?\s*$/m,
      "the Copilot orchestrator pin changed — the preserved rationale says verify against the Copilot CLI first",
    );
  });
});
